language: go
sudo: required
services:
- docker
go: 1.9
after_success: |
  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    bash <(curl -s https://codecov.io/bash)
    make docker-push

    sed \
      -e "s|\${CHARTS_DATABASE_PASS}|${CHARTS_DATABASE_PASS}|g" \
      -e "s|\${CHARTS_DATABASE_DIR}|${CHARTS_DATABASE_DIR}|g" \
      -e "s|\${READINGS_DATABASE_PASS}|${READINGS_DATABASE_PASS}|g" \
      -e "s|\${READINGS_DATABASE_DIR}|${READINGS_DATABASE_DIR}|g" \
      docker-compose.yml > docker-compose-env.yml
  fi
notifications:
  email: false
deploy:
- provider: script
  skip_cleanup: true
  script: "curl -H 'Authorization: GitHub ${GITHUB_OAUTH_TOKEN}' -X POST https://dashboard-api.vibioh.fr/containers/eponae_api/ --data-binary @docker-compose-env.yml"
  on:
    branch: master
