language: go
sudo: required
services:
- docker
go: 1.9
install: make
script: |
  DOCKER_IMAGE_NAME=${DOCKER_USER}/eponae-api
  curl -o cacert.pem https://curl.haxx.se/ca/cacert.pem &&
  ./blueprint.sh &&
  docker build -t ${DOCKER_IMAGE_NAME} .
after_success: |
  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    bash <(curl -s https://codecov.io/bash) &&
    docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} && docker push ${DOCKER_IMAGE_NAME}

    sed \
      -e "s|\${CHARTS_DATABASE_PASS}|${CHARTS_DATABASE_PASS}|g" \
      -e "s|\${READINGS_DATABASE_PASS}|${READINGS_DATABASE_PASS}|g" \
      -e "s|\${USERS}|${USERS}|g" \
      docker-compose.yml > docker-compose-env.yml
  fi
notifications:
  email: false
deploy:
- provider: script
  skip_cleanup: true
  script: "curl -H 'Authorization: GitHub ${GITHUB_OAUTH_TOKEN}' -X POST https://dashboard-api.vibioh.fr/containers/eponae_api/ --data-binary @docker-compose-env.yml"
  on:
    branch: master
