jobs:
  include:
  - stage: Build

    language: go
    sudo: required
    services:
    - docker
    go : '1.10'
    script: |
      npm run build && \
      docker build -t ${DOCKER_USER}/eponae-api .
    after_success: |
      if [ "${TRAVIS_BRANCH}" == "master" ]; then
        bash <(curl -s https://codecov.io/bash)
        curl -s -X POST https://goreportcard.com/checks?repo=github.com/ViBiOh/eponae-api

        make docker-push
      fi

  - stage: Deploy

    script: |
      sed \
        -e "s|\${EPONAE_DATABASE_HOST}|${EPONAE_DATABASE_HOST}|g" \
        -e "s|\${EPONAE_DATABASE_USER}|${EPONAE_DATABASE_USER}|g" \
        -e "s|\${EPONAE_DATABASE_PASS}|${EPONAE_DATABASE_PASS}|g" \
        -e "s|\${EPONAE_DATABASE_NAME}|${EPONAE_DATABASE_NAME}|g" \
        docker-compose.yml > docker-compose-env.yml
    deploy:
      provider: script
      skip_cleanup: true
      script: 'curl -H "Authorization: GitHub ${GITHUB_OAUTH_TOKEN}" -X POST https://dashboard-api.vibioh.fr/containers/eponae_api/ --data-binary @docker-compose.yml'

stages:
  - Build
  - name: Deploy
    if: branch = master

notifications:
  email: false
