version: '2.1'

services:
  api:
    image: vibioh/eponae-api
    command:
    - -csp
    - "default-src 'self'; base-uri 'self'; script-src 'self' 'unsafe-inline' unpkg.com/swagger-ui-dist@3/; style-src 'self' 'unsafe-inline' unpkg.com/swagger-ui-dist@3/; img-src 'self' data:; connect-src 'self' api.eponae.fr"
    - -dbHost
    - ${EPONAE_DATABASE_HOST}
    - -dbUser
    - ${EPONAE_DATABASE_USER}
    - -dbPass
    - ${EPONAE_DATABASE_PASS}
    - -dbName
    - ${EPONAE_DATABASE_NAME}
    - -tracingAgent
    - monitoring_jaeger_1:6831
    - -tracingName
    - eponae_api
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: api.eponae.fr'
      traefik.protocol: 'http'
      traefik.port: '1080'
      traefik.frontend.rateLimit.extractorFunc: 'client.ip'
      traefik.frontend.rateLimit.rateSet.first.period: '60s'
      traefik.frontend.rateLimit.rateSet.first.average: '100'
      traefik.frontend.rateLimit.rateSet.first.burst: '200'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 25165824
    security_opt:
    - no-new-privileges
