version: '2.1'

services:
  api:
    image: vibioh/eponae-api
    command:
    - -csp
    - "default-src 'self'; script-src 'unsafe-inline' ajax.googleapis.com cdnjs.cloudflare.com; style-src 'unsafe-inline' cdnjs.cloudflare.com fonts.googleapis.com; font-src data: fonts.gstatic.com cdnjs.cloudflare.com; img-src data:"
    - -eponaeDbHost
    - eponae_db
    - -eponaeDbUser
    - eponae
    - -eponaeDbPass
    - ${EPONAE_DATABASE_PASS}
    - -eponaeDbName
    - eponae
    - -readingsAuthUsers
    - eponae:admin
    - -readingsBasicUsers
    - 1:eponae:$$2a$$12$$CTmdj1LZIt/5fYYC/xxS4u7iwGA/FBEp2q3ewCzySbV4P4o4Yjc0W
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: api.eponae.fr'
      traefik.protocol: 'https'
      traefik.port: '1080'
      traefik.backend.maxconn.amount: '16'
      traefik.backend.maxconn.extractorfunc: 'client.ip'
      traefik.frontend.rateLimit.extractorFunc: 'client.ip'
      traefik.frontend.rateLimit.rateSet.first.period: '60s'
      traefik.frontend.rateLimit.rateSet.first.average: '100'
      traefik.frontend.rateLimit.rateSet.first.burst: '200'
    external_links:
    - eponae_db_1:eponae_db
    logging:
      driver: json-file
      options:
        max-size: '10m'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 25165824
    security_opt:
    - no-new-privileges

networks:
  default:
    external:
      name: traefik
